# Generated by Django 6.1.1 on 2026-09-29 03:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarroArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado y Confirmado'), ('ENTREGADO', 'Maquinaria Entregada en Terreno'), ('COMPLETADO', 'Arriendo Completado y Devuelto'), ('CANCELADO', 'Contrato Cancelado')], default='PENDIENTE', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=12)),
                ('garantia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidades_disponibles', models.PositiveIntegerField(default=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinarias', to='arriendos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('tarifa_diaria_historica', models.DecimalField(decimal_places=2, max_digits=12)),
                ('garantia_historica', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arriendos.contrato')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arriendos.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='CarroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arriendos.carroarriendo')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arriendos.maquinaria')),
            ],
        ),
    ]
