# Generated by Django 6.1.1 on 2026-09-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carroitem',
            old_name='cantidad',
            new_name='dias',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='maquinaria',
            old_name='unidades_disponibles',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='carroarriendo',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='carroitem',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='carroitem',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='garantia',
        ),
        migrations.RemoveField(
            model_name='maquinaria',
            name='tarifa_diaria',
        ),
        migrations.AddField(
            model_name='contrato',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='precio_diario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENTREGADO', 'Entregado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ContratoItem',
        ),
    ]
